name: container-deployment

on:
  push:
    branches: ['github-action']
    paths:
      - 'containerMf/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run
      - run: npm run buildContainer
      - run: npm run buildAuthMf
